### ISSUE TITLE
Color isn't changed when the "Change Color" button is clicked.

### ISSUE THREAD

**Issue by Ganesaperumal** [divyawork/ppstrom#161]
Hi @divyawork, please fix the issue in the project of "Background Color Changer" [html file](https://github.com/divyawork/ppstrom/blob/main/Ganesaperumal/index.html). When I click the **_"Change Color"_** button, Background color doesn't change. 
![Screenshot 2023-11-23 103717](https://github.com/divyawork/ppstrom/assets/58650987/323f0adb-794b-4d66-b53f-0ee064878a7a)

**Comment by divyawork** [comment]
Ganesh you did't mention the  name/code color in js ,i think that's the issue ..can you check it once...if it's not the issue will check further. 

![issue](https://github.com/divyawork/ppstrom/assets/110908007/f4b42bd4-0c74-422b-908b-56873805c7e7)

**Comment by Ganesaperumal** [comment]
#163 Thank you Ma'm It's resolved
